// <auto-generated />
namespace Sens_Hospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nodir_donate04082021357 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nodir_donate04082021357));
        
        string IMigrationMetadata.Id
        {
            get { return "202104081958087_nodir_donate04082021357"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
