// <auto-generated />
namespace Sens_Hospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update04082021257 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update04082021257));
        
        string IMigrationMetadata.Id
        {
            get { return "202104081857052_update04082021257"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
